name: flutter_app_vertex_ai_agent
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_ai: ^2.0.0
  firebase_core: ^3.13.1
  path_provider: ^2.1.5
  flutter_dotenv: ^5.2.1
  video_player: ^2.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/
    - .env
  
  


